services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn social_network.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - prod_app_data:/var/lib/prod_app_data/data/
      - ./db-init:/docker-entrypoint-initdb.d/
    env_file:
      - ./.env.prod
  redis:
    image: "redis:alpine"
    ports:
      - ${REDIS_PORT}:6379
    env_file:
      - ./.env.prod

volumes:
  prod_app_data: