# Generated by Django 5.1.1 on 2024-10-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blockeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('read', 'read'), ('write', 'write'), ('admin', 'admin')], default='write', max_length=20),
        ),
    ]
