# Generated by Django 5.1.1 on 2024-10-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
